app = "lux-bot"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  COMMAND_PREFIX = "!"
  LOG_LEVEL = "info"

[[mounts]]
  source = "lux_auth"
  destination = "/app/core/auth"

[[mounts]]
  source = "lux_db"
  destination = "/app/db"
