app = "lux-bot"

primary_region = "ams" # or your closest region

[build]
  dockerfile = "Dockerfile"

[env]
  COMMAND_PREFIX = "!"
  LOG_LEVEL = "info"

[mounts]
  source="lux_data"
  destination="/app"
